spring:
  application:
    name: ElasticsearchSpringData

server:
  port: 8888
  servlet:
    context-path: \

springdoc:
  swagger-ui:
    use-root-path: true
  version: "@springdoc.version@"

elasticsearch.url: http://localhost:9200

---
spring.config.activate.on-profile: docker
elasticsearch.url: elasticsearch
